# Generated by Django 4.0.6 on 2022-07-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
