# Generated by Django 4.0.6 on 2022-07-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_alter_speaker_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=20),
        ),
    ]
