# Generated by Django 4.0.6 on 2022-07-26 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_participant_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
