# Generated by Django 4.0.6 on 2022-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_conference_created_conference_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
