# Generated by Django 4.0.6 on 2022-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_conference_con_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('BED', 'Back End Developer'), ('FED', 'Front End Developer'), ('FSD', 'Full Stack Developer'), ('DES', 'Designer'), ('STU', 'Student'), ('ENT', 'Enthusiast'), ('OTH', 'Other')], default='OTH', max_length=100),
            preserve_default=False,
        ),
    ]
